### PR TITLE
Get to build on MacOS

### PR DESCRIPTION
**Pull request by hpux735**
I don't know if you're interested, but I made a few changes that let this build on mac and linux

### CODE REVIEW

**Comment by itssofluffy** [comment]
Thank you, i don't have access to a Mac so should really invest some time on travis

**Comment by hpux735** [comment]
Thanks for merging!  I've got one for Mutex as well.  I'll get it to you in a few :)

**Comment by hpux735** [comment]
Oh, one other thing, would you mind tagging it for the package manager?

**Comment by itssofluffy** [comment]
Sorry about that, done!

**Pull request merged**
